apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
  namespace: tekton-demo
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git@github.com:idefav/tekton-demo.git
