apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-to-image
  namespace: tekton-demo
spec:
  workspaces:
    - name: source
    - name: m2
      mountPath: /root/.m2
    - name: m2-settings
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
  steps:
    - name: maven
      image: maven:3.5.0-jdk-8-alpine
      workingDir: $(workspaces.source.path)
      command:
        - mvn
      args:
        - "-s $(workspaces.m2-settings.path)/settings.xml"
        - clean
        - install
        - -DskipTests
      volumeMounts:
        - name: m2
          mountPath: /root/.m2
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)
        - --context=/workspace/git-source/$(inputs.params.pathToContext)